version: 2

multi-ecosystem-groups:
  all-dependencies:
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/London"
    labels:
      - "dependencies"

updates:
  - package-ecosystem: "pip"
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: "all-dependencies"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "python"
    versioning-strategy: "increase"

  - package-ecosystem: "github-actions"
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: "all-dependencies"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
    labels:
      - "github-actions"

  - package-ecosystem: "docker"
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: "all-dependencies"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
    labels:
      - "docker"

  - package-ecosystem: "pre-commit"
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: "all-dependencies"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
    labels:
      - "pre-commit"
