---

stages:
  - code-quality
  - build
  - test
  - publish

variables:
  APPLICATION: gitlab-docs
image: python:3.12
default:
  tags:
    - gitlab-org
megalinter:
  stage: code-quality
  image: oxsecurity/megalinter-python:v8.0.0
  script: [ "true" ] # if script: ["true"] doesn't work, you may try ->  script: [ "/bin/bash /entrypoint.sh" ]
  variables:
    # All available variables are described in documentation
    # https://megalinter.io/configuration/
    DEFAULT_WORKSPACE: $CI_PROJECT_DIR
    # ADD YOUR CUSTOM ENV VARIABLES HERE TO OVERRIDE VALUES OF .mega-linter.yml AT THE ROOT OF YOUR REPOSITORY
  artifacts:
    when: always
    paths:
      - megalinter-reports
    expire_in: 1 week

build:
  stage: build
  needs: []
  script:
    # install poetry for managing application
    - make init
    - export PATH="/root/.local/bin:$PATH"
    - poetry --version
    - poetry build
    # - latest_build=$(ls ./dist/*.tar.gz)
    - pip3 install $(ls ./dist/*.tar.gz)







