- id: gitlab-docs
  name: gitlab-docs
  description: Automatically update GitLab pipeline documentation in README.md
  entry: gitlab-docs
  additional_dependencies:
    - gitlab_docs

  language_version: python3.12
  pass_filenames: false
  files: \.(yml|yaml)$
