---
- id: gitlab-docs
  name: gitlab-docs
  description: Documents Gitlab CI Yaml
  types: [file, yaml]
  language: docker_image
  pass_filenames: true
  # args: [ 'test', '--only-k8s-files' ]
  entry: --user root charlieasmith93/gitlab-docs:latest
