repos:
  - repo: local
    hooks:
      - id: gitlab-compliance
        name: Run compliance smoke check
        entry: bash -c 'poetry run gitlab-compliance compliance -f tests/compliance_policies/passing -p examples/sample-files/.gitlab-ci.yml'
        language: system
        pass_filenames: false
        files: \.(yml|yaml)$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        files: ^(src|tests)/

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        files: ^(src|tests)/

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        files: ^(src|tests)/
        args:
          - --max-line-length=88
          - --extend-ignore=E203,W503,F401,F841,E501

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.7
    hooks:
      - id: bandit
        args: ["-r", "src", "-s", "B101"]
        pass_filenames: false
