- id: gitlab-compliance
  name: gitlab-compliance
  description: Automatically update GitLab pipeline documentation in README.md
  entry: gitlab-compliance
  additional_dependencies:
    - gitlab-compliance

  language_version: python3.12.11
  pass_filenames: false
  files: \.(yml|yaml)$
