version: "3.9"

services:
  gitlab-docs-alpine:
    build:
      context: .
      dockerfile: Dockerfile
      target: alpine
    image: gitlab-docs:alpine
    container_name: gitlab-docs-alpine
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    read_only: true
    command: ["gitlab-docs", "--help"]

  gitlab-docs-slim:
    build:
      context: .
      dockerfile: Dockerfile
      target: slim
    image: gitlab-docs:slim
    container_name: gitlab-docs-slim
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    read_only: true
    command: ["gitlab-docs", "--help"]
