# .pre-commit-hooks.yaml
- id: gitlab-docs
  name: Run GitLab Docs
  description: Automatically update GitLab pipeline documentation in README.md
  entry: gitlab-docs
  language: system
  pass_filenames: false
