[project]
name = "gitlab-compliance"
dynamic = [ "readme" ]
[project.urls]
"Home Page" = "https://maturitybuilder.github.io/gitlab-compliance/"
DOCUMENTATION = "https://maturitybuilder.github.io/gitlab-compliance/"
Repository = "https://github.com/MaturityBuilder/gitlab-compliance"

[tool.poetry_bumpversion.file."src/__init__.py"]

[tool.poetry]
name = "gitlab-compliance"
version = "1.0.6"
description = "Gitlab automatically generates gitlab documentation from yaml files"
authors = ["Charlie Smith <me@charlieasmith.co.uk>"]
readme = ["docs/index.md"]

packages = [{ include = "src" }]



[tool.poetry.dependencies]
python = "<3.13,>=3.12"
prettytable = "*"
pytablewriter = "1.2.0"
oyaml = "*"
typer = "0.10.0"
markdown-analysis = "0.1.5"
urllib3 = "2.7.0"
jq = "1.8.0"
click = "8.0.0"
semver = "3.0.2"
pyyaml = "6.0.2"
loguru = "0.7.0"
python-gitlab = "7.0.0"
rich = "14.2.0"
oras = "0.2.42"
idna = "3.15"
requests = "2.34.2"
behave = "^1.2.6"

[tool.poetry.scripts]
gitlab-docs = 'src.gitlab_compliance:gitlab_compliance'
gitlab-compliance = 'src.gitlab_compliance:gitlab_compliance'

[tool.poetry.group.dev.dependencies]
setuptools = "83.0.0"
pytest = "^8.4.1"
pre-commit = "^4.2.0"

pyyaml = "^6.0.2"
coverage = "^7.9.2"

[tool.black]
line-length = 88

[tool.isort]
profile = "black"

[tool.flake8]
max-line-length = 88
extend-ignore = ["E203", "W503"]

[tool.poetry.group.docs.dependencies]
mkdocs = "^1.6.0"
mkdocs-material = "^9.6.0"
[build-system]
requires = ["poetry-core","setuptools","poetry-bumpversion","id"]
build-backend = "poetry.core.masonry.api"
