[tool.poetry]
name = "gitlab-docs"
version = "1.0.7"
description = "GitLab CI pipeline documentation and Gherkin-based compliance checks"
authors = ["Charlie Smith <me@charlieasmith.co.uk>"]
readme = ["docs/index.md", "docs/command-reference.md", "docs/output-example.md"]
packages = [{ include = "src" }]

[tool.poetry.dependencies]
python = "<3.13,>=3.12"
prettytable = "*"
pytablewriter = { version = "1.2.0", extras = ["html"] }
oyaml = "*"
typer = "0.10.0"
markdown-analysis = "0.1.5"
setuptools = "83.0.0"
urllib3 = "2.7.0"
jq = "1.8.0"
click = "8.0.0"
semver = "3.0.2"
pyyaml = "6.0.2"
loguru = "0.7.0"
python-gitlab = "7.0.0"
rich = "14.2.0"
oras = "0.2.42"
idna = "3.15"
requests = "2.34.2"
[tool.poetry.scripts]
gitlab-compliance = 'src.gitlab_docs:gitlab_compliance'
gitlab-docs = 'src.gitlab_docs:gitlab_compliance'

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.1"
behave = "^1.2.6"
coverage = "^7.9.2"
md-click = "^1.0.1"
pre-commit = "^4.0.0"

[project]
name = "gitlab-docs"
dynamic = ["readme"]

[project.urls]
"Home Page" = "https://pypi.org/manage/project/gitlab-docs"
DOCUMENTATION = "https://pypi.org/manage/project/gitlab-docs"
Repository = "https://gitlab.com/charlieasmith/gitlab-docs"
Gitlab = "https://gitlab.com/charlieasmith/gitlab-docs"

[tool.poetry_bumpversion.file."src/__init__.py"]

[build-system]
requires = ["poetry-core>=1.9.0"]
build-backend = "poetry.core.masonry.api"
