#!/usr/bin/env python3
"""Generate happy/sad 10-hop nested ``include: local:`` shell-check fixtures.

Depth model (matches tests/fixtures/nested-includes language):
  - Root ``.gitlab-ci.yml`` is depth 0
  - ``layers/layer-01.yml`` … ``layer-10.yml`` are hops 1–10
  - Each hop defines a realistic CI job; leaf also defines ``nested_leaf_*``

Run from repo root or this directory:

    python tests/fixtures/shell_check/nested-10/generate.py
"""

from __future__ import annotations

from pathlib import Path

DEPTH = 10
ROOT = Path(__file__).resolve().parent

# Deterministic themed jobs — one primary job per hop (1–10).
LAYER_JOBS: list[tuple[str, str, str]] = [
    (
        "tflint",
        "lint",
        """\
    - set -euo pipefail
    - echo "tflint hop=${LAYER_HOP}"
    - tflint --chdir="$CI_PROJECT_DIR"
""",
    ),
    (
        "terraform_plan",
        "plan",
        """\
    - set -euo pipefail
    - terraform version
    - terraform plan -input=false -out="$CI_PROJECT_DIR/plan.cache"
""",
    ),
    (
        "docker_scan",
        "security",
        """\
    - set -euo pipefail
    - docker run --rm aquasec/trivy:0.50.1 image "python:3.12.0"
""",
    ),
    (
        "hadolint",
        "lint",
        """\
    - set -euo pipefail
    - hadolint --version
    - hadolint "$CI_PROJECT_DIR/Dockerfile"
""",
    ),
    (
        "kube_linter",
        "lint",
        """\
    - set -euo pipefail
    - kube-linter lint "$CI_PROJECT_DIR/deploy/"
""",
    ),
    (
        "ansible_lint",
        "lint",
        """\
    - set -euo pipefail
    - ansible-lint --version
    - ansible-lint "$CI_PROJECT_DIR/playbooks/"
""",
    ),
    (
        "checkov_scan",
        "security",
        """\
    - set -euo pipefail
    - checkov -d "$CI_PROJECT_DIR/terraform" --framework terraform
""",
    ),
    (
        "gitleaks",
        "security",
        """\
    - set -euo pipefail
    - gitleaks detect --source="$CI_PROJECT_DIR" --no-git
""",
    ),
    (
        "semgrep_sast",
        "security",
        """\
    - set -euo pipefail
    - semgrep --config=p/ci --error "$CI_PROJECT_DIR"
""",
    ),
    (
        "container_build",
        "build",
        """\
    - set -euo pipefail
    - docker build -t "app:${CI_COMMIT_SHA}" "$CI_PROJECT_DIR"
    - docker run --rm "python:3.12.0" python --version
""",
    ),
]

HAPPY_LEAF_SCRIPT = """\
    - set -euo pipefail
    - apk add --no-cache jq=1.7.1-r0
    - echo "commit=${CI_COMMIT_SHA}"
    - value="$(echo hi)"
    - check="$(echo "$HOSTNAME" | tr '[:lower:]' '[:upper:]')"
    - echo "${APP_NAME:-nested-demo}"
    - tmp="$(mktemp)"
    - echo "ok" >"$tmp"
    - if [ "$CI_COMMIT_SHA" = "abc" ]; then echo ok; fi
"""

SAD_LEAF_SCRIPT = """\
    - echo $UNQUOTED
    - cd $HOME
    - value=$(echo hi)
    - apk add curl
    - pip install requests
    - docker pull nginx
    - check=$(curl $HOSTNAME | jq -r '.message')
    - echo "$PREFIX"$SUFFIX
"""

STAGES = """\
stages:
  - prepare
  - lint
  - plan
  - build
  - security
  - verify
"""


def _layer_name(n: int) -> str:
    return f"layer-{n:02d}.yml"


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"wrote {path.relative_to(ROOT)}")


def _job_block(name: str, stage: str, script: str, *, hop: int) -> str:
    # Inject hop marker without breaking quoting policies.
    script = script.replace("${LAYER_HOP}", str(hop))
    return f"""\
{name}:
  stage: {stage}
  variables:
    LAYER_HOP: "{hop}"
  script:
{script}
"""


def _root_yaml(*, include_path: str, root_job: str, root_script: str) -> str:
    return f"""\
# Generated by generate.py — do not edit by hand; re-run the generator.
# Depth 0 root: includes hop 1, defines a small root job.
{STAGES}
variables:
  APP_NAME: nested-demo

include:
  - local: {include_path}

{root_job}:
  stage: prepare
  script:
{root_script}
"""


def _mid_layer_yaml(
    *, next_layer: str, hop: int, job_name: str, stage: str, script: str
) -> str:
    return f"""\
# Generated by generate.py — mid-hop {hop:02d} include + themed job.
include:
  - local: {next_layer}

{_job_block(job_name, stage, script, hop=hop)}
"""


def _leaf_yaml(
    *,
    hop: int,
    themed_name: str,
    themed_stage: str,
    themed_script: str,
    leaf_job: str,
    leaf_script: str,
) -> str:
    return f"""\
# Generated by generate.py — hop {hop} leaf (themed job + nested leaf job).
{_job_block(themed_name, themed_stage, themed_script, hop=hop)}
{leaf_job}:
  stage: verify
  script:
{leaf_script}
"""


def generate_tree(
    tree: str,
    *,
    leaf_job: str,
    leaf_script: str,
    root_job: str,
    root_script: str,
) -> None:
    base = ROOT / tree
    layers = base / "layers"
    _write(
        base / ".gitlab-ci.yml",
        _root_yaml(
            include_path=f"layers/{_layer_name(1)}",
            root_job=root_job,
            root_script=root_script,
        ),
    )
    for n in range(1, DEPTH):
        job_name, stage, script = LAYER_JOBS[n - 1]
        _write(
            layers / _layer_name(n),
            _mid_layer_yaml(
                next_layer=_layer_name(n + 1),
                hop=n,
                job_name=job_name,
                stage=stage,
                script=script,
            ),
        )
    leaf_themed, leaf_stage, leaf_themed_script = LAYER_JOBS[DEPTH - 1]
    _write(
        layers / _layer_name(DEPTH),
        _leaf_yaml(
            hop=DEPTH,
            themed_name=leaf_themed,
            themed_stage=leaf_stage,
            themed_script=leaf_themed_script,
            leaf_job=leaf_job,
            leaf_script=leaf_script,
        ),
    )


def main() -> None:
    happy_root_script = """\
    - set -euo pipefail
    - echo "root ok"
"""
    sad_root_script = """\
    - set -euo pipefail
    - echo "root ok"
"""
    generate_tree(
        "happy",
        leaf_job="nested_leaf_happy",
        leaf_script=HAPPY_LEAF_SCRIPT,
        root_job="root_job",
        root_script=happy_root_script,
    )
    generate_tree(
        "sad",
        leaf_job="nested_leaf_sad",
        leaf_script=SAD_LEAF_SCRIPT,
        root_job="root_job",
        root_script=sad_root_script,
    )
    print(f"generated {DEPTH}-hop happy/ and sad/ trees under {ROOT}")


if __name__ == "__main__":
    main()
