#!/usr/bin/env python3
"""Generate happy/sad 10-hop nested ``include: local:`` shell-check fixtures.

Depth model (matches tests/fixtures/nested-includes language):
  - Root ``.gitlab-ci.yml`` is depth 0
  - ``layers/layer-01.yml`` … ``layer-10.yml`` are hops 1–10
  - Leaf job is defined only in ``layer-10.yml``

Run from repo root or this directory:

    python tests/fixtures/shell_check/nested-10/generate.py
"""

from __future__ import annotations

from pathlib import Path

DEPTH = 10
ROOT = Path(__file__).resolve().parent

HAPPY_LEAF_SCRIPT = """\
    - set -euo pipefail
    - apk add --no-cache jq=1.7.1-r0
    - echo "commit=${CI_COMMIT_SHA}"
    - value="$(echo hi)"
    - check="$(echo "$HOSTNAME" | tr '[:lower:]' '[:upper:]')"
    - echo "${APP_NAME:-nested-demo}"
    - tmp="$(mktemp)"
    - echo "ok" >"$tmp"
    - if [ "$CI_COMMIT_SHA" = "abc" ]; then echo ok; fi
"""

SAD_LEAF_SCRIPT = """\
    - echo $UNQUOTED
    - cd $HOME
    - value=$(echo hi)
    - apk add curl
    - pip install requests
    - docker pull nginx
    - check=$(curl $HOSTNAME | jq -r '.message')
    - echo "$PREFIX"$SUFFIX
"""


def _layer_name(n: int) -> str:
    return f"layer-{n:02d}.yml"


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"wrote {path.relative_to(ROOT)}")


def _root_yaml(*, include_path: str, root_job: str, root_script: str) -> str:
    return f"""\
# Generated by generate.py — do not edit by hand; re-run the generator.
# Depth 0 root: includes hop 1, defines a small root job.
stages:
  - prepare
  - verify

variables:
  APP_NAME: nested-demo

include:
  - local: {include_path}

{root_job}:
  stage: prepare
  script:
{root_script}
"""


def _mid_layer_yaml(*, next_layer: str) -> str:
    return f"""\
# Generated by generate.py — mid-hop passthrough include.
include:
  - local: {next_layer}
"""


def _leaf_yaml(*, job_name: str, script_block: str) -> str:
    return f"""\
# Generated by generate.py — hop {DEPTH} leaf (job defined only here).
{job_name}:
  stage: verify
  script:
{script_block}
"""


def generate_tree(
    tree: str,
    *,
    leaf_job: str,
    leaf_script: str,
    root_job: str,
    root_script: str,
) -> None:
    base = ROOT / tree
    layers = base / "layers"
    _write(
        base / ".gitlab-ci.yml",
        _root_yaml(
            include_path=f"layers/{_layer_name(1)}",
            root_job=root_job,
            root_script=root_script,
        ),
    )
    for n in range(1, DEPTH):
        _write(layers / _layer_name(n), _mid_layer_yaml(next_layer=_layer_name(n + 1)))
    _write(
        layers / _layer_name(DEPTH),
        _leaf_yaml(job_name=leaf_job, script_block=leaf_script),
    )


def main() -> None:
    happy_root_script = """\
    - set -euo pipefail
    - echo "root ok"
"""
    sad_root_script = """\
    - set -euo pipefail
    - echo "root ok"
"""
    generate_tree(
        "happy",
        leaf_job="nested_leaf_happy",
        leaf_script=HAPPY_LEAF_SCRIPT,
        root_job="root_job",
        root_script=happy_root_script,
    )
    generate_tree(
        "sad",
        leaf_job="nested_leaf_sad",
        leaf_script=SAD_LEAF_SCRIPT,
        root_job="root_job",
        root_script=sad_root_script,
    )
    print(f"generated {DEPTH}-hop happy/ and sad/ trees under {ROOT}")


if __name__ == "__main__":
    main()
