"""GitLab merge request helpers for compliance check."""

from __future__ import annotations

import os
import re

import gitlab

from src.compliance.api_config import resolve_project
from src.compliance.console import print_info, print_success, print_warning

_FIX_PATH_RE = re.compile(r"\((?:[^()]*?,\s*)?(?P<path>[^(),]+):(?P<line>\d+)\)\s*$")
_MR_TITLE = "fix: gitlab-compliance supply-chain updates"
_DEFAULT_SOURCE_BRANCH = "gitlab-compliance/supply-chain-fix"


def _resolve_gitlab_url(gitlab_url: str | None) -> str:
    return (
        gitlab_url
        or os.getenv("CI_SERVER_URL")
        or os.getenv("GITLAB_URL")
        or "https://gitlab.com"
    )


def _resolve_project_path(project: str | None) -> str:
    resolved = project or resolve_project(None)
    if not resolved:
        raise ValueError(
            "GitLab project is required. Set --project or CI_PROJECT_PATH."
        )
    return resolved


def _changed_files_from_fix_messages(fix_messages: list[str]) -> list[str]:
    paths: list[str] = []
    seen: set[str] = set()
    for message in fix_messages:
        match = _FIX_PATH_RE.search(message)
        if not match:
            continue
        path = match.group("path").strip()
        if path and path not in seen:
            seen.add(path)
            paths.append(path)
    return paths


def _repo_relative_path(path: str, pipeline_file: str) -> str:
    abs_path = os.path.realpath(os.path.abspath(path))
    roots: list[str] = []
    project_dir = os.getenv("CI_PROJECT_DIR")
    if project_dir:
        roots.append(os.path.realpath(project_dir))
    roots.append(os.path.realpath(os.getcwd()))
    roots.append(os.path.dirname(os.path.realpath(os.path.abspath(pipeline_file))))
    for root in roots:
        try:
            if os.path.commonpath([root, abs_path]) == root:
                return os.path.relpath(abs_path, root).replace(os.sep, "/")
        except ValueError:
            continue
    return path.replace(os.sep, "/")


def _default_branch_name() -> str:
    """Stable source branch so re-runs update the same open MR."""
    return _DEFAULT_SOURCE_BRANCH


def _mr_description(
    fix_messages: list[str],
    *,
    files_updated: int,
) -> str:
    """Render a readable MR body for supply-chain fix commits."""
    lines = [
        "## Supply-chain compliance fix",
        "",
        "This merge request was created by "
        "[`gitlab-compliance check --fix-supply-chain/--fix-policies --create-mr`]"
        "(https://maturitybuilder.github.io/gitlab-compliance/) "
        "to apply automated supply-chain and/or allowlisted policy remediations "
        "to GitLab CI YAML.",
        "",
        "### Summary",
        "",
        "| | |",
        "| --- | --- |",
        f"| Files updated | `{files_updated}` |",
        f"| Changes applied | `{len(fix_messages)}` |",
        "",
        "### Changes",
        "",
    ]
    if fix_messages:
        for index, message in enumerate(fix_messages, start=1):
            lines.append(f"{index}. {message}")
    else:
        lines.append("_No change details were recorded._")

    lines.extend(
        [
            "",
            "### Review notes",
            "",
            "- Confirm each pin or version bump is intentional for this project.",
            "- Re-running fix flags with `--create-mr` updates this branch and MR "
            "(or reopens a closed MR for the same branch) instead of opening a duplicate.",
            "",
            "---",
            "",
            "*Generated by "
            "[gitlab-compliance](https://maturitybuilder.github.io/gitlab-compliance/).*",
        ]
    )
    return "\n".join(lines)


def _friendly_gitlab_error(exc: Exception, *, action: str) -> ValueError:
    detail = str(exc).strip() or exc.__class__.__name__
    return ValueError(f"GitLab API error while {action}: {detail}")


def _find_reusable_merge_request(project_obj, *, source_branch: str):
    """Return ``(merge_request, action)`` where action is ``update`` or ``reopen``."""
    opened = project_obj.mergerequests.list(
        state="opened",
        source_branch=source_branch,
        get_all=True,
    )
    if opened:
        return opened[0], "update"

    closed = project_obj.mergerequests.list(
        state="closed",
        source_branch=source_branch,
        get_all=True,
    )
    if closed:
        return closed[0], "reopen"
    return None, None


def _mr_label(merge_request) -> str:
    web_url = getattr(merge_request, "web_url", None) or ""
    return web_url or f"!{merge_request.iid}"


def _mr_return_value(merge_request) -> str:
    web_url = getattr(merge_request, "web_url", None) or ""
    return web_url or str(merge_request.iid)


def create_supply_chain_merge_request(
    *,
    pipeline_file: str,
    fix_messages: list[str],
    gitlab_url: str | None,
    token: str,
    project: str | None,
    branch_name: str | None = None,
    target_branch: str | None = None,
) -> str | None:
    """Commit fixed files and open, update, or reopen an MR."""
    if not token:
        raise ValueError(
            "--create-mr requires a GitLab token (--token, GITLAB_TOKEN, or CI_JOB_TOKEN)"
        )
    changed = _changed_files_from_fix_messages(fix_messages)
    if not changed:
        print_info(
            "No supply-chain file changes to commit; skipping --create-mr.",
            title="Merge request skipped",
        )
        return None

    existing_files: list[str] = []
    for path in changed:
        if os.path.exists(path):
            existing_files.append(path)
        else:
            print_warning(
                f"Skipping missing fixed file for MR: {path}",
                title="Missing file",
            )
    if not existing_files:
        print_info(
            "No readable fixed files for MR commit; skipping --create-mr.",
            title="Merge request skipped",
        )
        return None

    project_path = _resolve_project_path(project)
    url = _resolve_gitlab_url(gitlab_url)

    try:
        gl = gitlab.Gitlab(url, private_token=token)
        project_obj = gl.projects.get(project_path)
        target = target_branch or project_obj.default_branch
        branch = branch_name or _default_branch_name()

        reusable_mr, mr_action = _find_reusable_merge_request(
            project_obj, source_branch=branch
        )

        try:
            project_obj.branches.get(branch)
        except gitlab.exceptions.GitlabGetError:
            project_obj.branches.create({"branch": branch, "ref": target})

        actions = []
        for path in existing_files:
            with open(path, encoding="utf-8") as handle:
                content = handle.read()
            actions.append(
                {
                    "action": "update",
                    "file_path": _repo_relative_path(path, pipeline_file),
                    "content": content,
                }
            )

        project_obj.commits.create(
            {
                "branch": branch,
                "commit_message": "fix: apply gitlab-compliance supply-chain updates",
                "actions": actions,
            }
        )

        description = _mr_description(
            fix_messages,
            files_updated=len(existing_files),
        )

        if reusable_mr is not None:
            if mr_action == "reopen":
                reusable_mr.state_event = "reopen"
            reusable_mr.title = _MR_TITLE
            reusable_mr.description = description
            reusable_mr.save()
            label = _mr_label(reusable_mr)
            verb = "Reopened" if mr_action == "reopen" else "Updated"
            print_success(
                f"{verb} merge request {label}\nBranch `{branch}` → `{target}`",
                title="Merge request",
            )
            return _mr_return_value(reusable_mr)

        merge_request = project_obj.mergerequests.create(
            {
                "source_branch": branch,
                "target_branch": target,
                "title": _MR_TITLE,
                "description": description,
                "remove_source_branch": True,
            }
        )
        label = _mr_label(merge_request)
        print_success(
            f"Created merge request {label}\nBranch `{branch}` → `{target}`",
            title="Merge request created",
        )
        return _mr_return_value(merge_request)
    except gitlab.exceptions.GitlabError as exc:
        raise _friendly_gitlab_error(exc, action="creating the merge request") from exc


def post_compliance_mr_comment(
    *,
    body: str,
    gitlab_url: str | None,
    token: str,
    project: str | None,
    mr_iid: int | None = None,
) -> None:
    """Post a note on an existing merge request."""
    if not token:
        raise ValueError(
            "--post-mr-comment requires a GitLab token "
            "(--token, GITLAB_TOKEN, or CI_JOB_TOKEN)"
        )
    resolved_iid = mr_iid
    if resolved_iid is None:
        env_iid = os.getenv("CI_MERGE_REQUEST_IID")
        if env_iid and env_iid.isdigit():
            resolved_iid = int(env_iid)
    if resolved_iid is None:
        raise ValueError("--post-mr-comment requires --mr-iid or CI_MERGE_REQUEST_IID.")

    project_path = _resolve_project_path(project)
    url = _resolve_gitlab_url(gitlab_url)
    try:
        gl = gitlab.Gitlab(url, private_token=token)
        project_obj = gl.projects.get(project_path)
        merge_request = project_obj.mergerequests.get(resolved_iid)
        merge_request.notes.create({"body": body})
    except gitlab.exceptions.GitlabError as exc:
        raise _friendly_gitlab_error(
            exc, action=f"posting a comment on !{resolved_iid}"
        ) from exc

    print_success(
        f"Posted compliance comment on merge request !{resolved_iid}",
        title="MR comment",
    )
