include:
  - project: "charlieasmith/a-generic-fragment"
    ref: main
    file: "a-fragment-file.yml"
  - project: "charlieasmith/a-generic-fragment-with-sem-version"
    ref: 1.0.0
    file: "a-fragment-file.yml"
gitleaks:
  stage: code-quality
  extends:
    - .gitleaks-template

shell-check:
  stage: code-quality
  extends:
    - .shell-check-template
  allow_failure: true
